"""create work_photos table

Revision ID: 4a2fb3cd2cce
Revises: c254fa701d7e
Create Date: 2026-08-19 22:15:39.376155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2fb3cd2cce'
down_revision: Union[str, Sequence[str], None] = 'c254fa701d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_work_entry_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name='check_work_photos_file_size_bytes'),
    sa.ForeignKeyConstraint(['daily_work_entry_id'], ['daily_work_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_photos_daily_work_entry_id'), 'work_photos', ['daily_work_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_photos_daily_work_entry_id'), table_name='work_photos')
    op.drop_table('work_photos')
    # ### end Alembic commands ###
