"""create daily_work_entries table

Revision ID: c254fa701d7e
Revises: 0930b36cb863
Create Date: 2026-08-19 21:27:34.542451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c254fa701d7e'
down_revision: Union[str, Sequence[str], None] = '0930b36cb863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_work_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cable_runs', sa.Integer(), nullable=False),
    sa.Column('cable_length_metres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('devices_installed', sa.Integer(), nullable=False),
    sa.Column('drilling_qty', sa.Integer(), nullable=False),
    sa.Column('mounting_qty', sa.Integer(), nullable=False),
    sa.Column('testing_qty', sa.Integer(), nullable=False),
    sa.Column('commissioning_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'approved', 'rejected', 'correction_required')", name='check_dwe_status'),
    sa.CheckConstraint('cable_length_metres >= 0', name='check_dwe_cable_length_metres'),
    sa.CheckConstraint('cable_runs >= 0', name='check_dwe_cable_runs'),
    sa.CheckConstraint('commissioning_qty >= 0', name='check_dwe_commissioning_qty'),
    sa.CheckConstraint('devices_installed >= 0', name='check_dwe_devices_installed'),
    sa.CheckConstraint('drilling_qty >= 0', name='check_dwe_drilling_qty'),
    sa.CheckConstraint('mounting_qty >= 0', name='check_dwe_mounting_qty'),
    sa.CheckConstraint('testing_qty >= 0', name='check_dwe_testing_qty'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_work_entries_attendance_record_id'), 'daily_work_entries', ['attendance_record_id'], unique=False)
    op.create_index('ix_daily_work_entries_employee_id_date', 'daily_work_entries', ['employee_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_work_entries_status'), 'daily_work_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_work_entries_status'), table_name='daily_work_entries')
    op.drop_index('ix_daily_work_entries_employee_id_date', table_name='daily_work_entries')
    op.drop_index(op.f('ix_daily_work_entries_attendance_record_id'), table_name='daily_work_entries')
    op.drop_table('daily_work_entries')
    # ### end Alembic commands ###
