"""create activities table

Revision ID: cf4af0901052
Revises: fd26e010edda
Create Date: 2026-08-19 21:05:13.623068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4af0901052'
down_revision: Union[str, Sequence[str], None] = 'fd26e010edda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=False),
    sa.Column('approved_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('cable', 'device', 'drilling', 'mounting', 'testing', 'commissioning')", name='check_activities_category'),
    sa.CheckConstraint('approved_rate >= 0', name='check_activities_approved_rate'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
