"""create work_orders table

Revision ID: fd26e010edda
Revises: 39af75e9b4d4
Create Date: 2026-08-19 19:40:25.283496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd26e010edda'
down_revision: Union[str, Sequence[str], None] = '39af75e9b4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_quantities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('billing_basis', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("billing_basis IN ('per_metre', 'per_device', 'lump_sum')", name='check_work_orders_billing_basis'),
    sa.CheckConstraint("status IN ('draft', 'open', 'in_progress', 'completed', 'closed')", name='check_work_orders_status'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_work_orders_dates'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_orders_site_id'), 'work_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_site_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
